# Start with CENTOS7
FROM centos:7
MAINTAINER Patrick Stowell<p.stowell@sheffield.ac.uk>
	
# Get Prereqs
RUN yum install -y \
    wget \
    git \
    cmake \
    gcc-c++ \
    gcc binutils \
    libX11-devel \
    libXpm-devel \
    libXft-devel \
    libXext-devel \
    gcc-gfortran \
    openssl-devel \
    pcre-devel \
    mesa-libGL-devel \
    mesa-libGLU-devel \
    glew-devel \
    ftgl-devel \
    mysql-devel \
    fftw-devel \
    cfitsio-devel \
    graphviz-devel \
    avahi-compat-libdns_sd-devel \
    libldap-dev python-devel \
    libxml2-devel \
    gsl-static \
    which \
    make \
    cvs \
    imake \
    autoconf \
    automake \
    libXt-devel \
    lesstif-devel \
    lesstif-dev \
    gmp-devel \
    open-motif-devel \
    gcc-gfortran \
    openssl-devel \
    pcre-devel \
    mesa-libGL-devel \
    mesa-libGLU-devel \
    glew-devel \
    ftgl-devel \
    mysql-devel \
    fftw-devel \
    cfitsio-devel \
    graphviz-devel \
    avahi-compat-libdns_sd-devel \
    libldap-dev \
    python-devel \
    libxml2-devel \
    libtool \
    gsl-static \
    subversion \
    emacs \
    gcc \
    procmail \
    patch \
    make \
    binutils \
    libX11-devel \
    libXpm-devel \
    libXft-devel \
    libXext-devel \
    gcc-gfortran \
    mysql-devel \
    fftw2 \
    graphviz-devel \
    avahi-devel \
    python-devel \
    libxml2-devel \
    openssl-devel \
    libdrm-devel \
    mesa-libGLU-devel \
    mesa-libGL-devel \
    glew-devel \
    ncurses-devel \
    openmotif 
    
